# CUDA
cuda_devices: '0,1'

# dataset
dataset:
  data_root: ''
  test_root: ''
  augment_data: false
  max_faces: 0

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average
