# CUDA
cuda_devices: '0'   # multi-gpu training is available

# dataset
dataset:
  data_root: '/content/main/MeshNet/datasets/shrec_21/fold_1_simplified/'
  augment_data: true
  max_faces: 15000

# result
ckpt_root: 'ckpt_root/'

# MeshNet
pretrained: ./weight/MeshNet_best_9192.pkl
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average

# train
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
batch_size: 4
max_epoch: 100
step_size: 75
gamma: 0.5
