# CUDA
cuda_devices: '0'   # multi-gpu training is available

# dataset
dataset:
  data_root: '/home/nhtlong/pmkhoi/shrec21/retrieval/MeshNet/datasets/datasetShape/simplified_folds/fold_4'
  augment_data: true
  max_faces: 20000

# result
ckpt_root: 'ckpt_root/shape/fold2-20k'

# MeshNet
pretrained: '/home/nhtlong/pmkhoi/shrec21/retrieval/MeshNet/weight/MeshNet_best_9192.pkl'
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average

# train
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
batch_size: 2
max_epoch: 120
step_size: 75
gamma: 0.5
